eureka: 
   client: 
    region: shenzheng
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
   instance:
    preferIpAddress: true
server: 
  port: 8762
  tomcat: 
    uri-encoding: UTF-8
spring:
  http: 
    encoding: 
      force:  true 
      charset:  UTF-8
      enabled:  true
  mvc:  
    message-codes-resolver:
      format: PREFIX_ERROR_CODE
    throw-exception-if-no-handler-found:  true
  resources:  
    add-mappings: false
  datasource:
    driver-class-name:  org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified
    username: postgres
    password: 123456
  rabbitmq: 
    host: localhost
    port: 5672
    username: appusername
    password: pdf8371759
  redis:  
    database: 0
    host: localhost
    port: 6379
    password: 
    pool: 
      max-active: 100
      max-wait: 100
      max-idle: 5
      min-idle: 1
    timeout:  3000
mybatis: 
     mapperLocations: classpath:mapper/*.xml
management:
     security:
         enabled:  false
my:
  test: 12345689110

  