eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
server:
  port: 8022
spring: 
  rabbitmq: 
    host: localhost
    port: 5672
    username: appusername
    password: pdf8371759