eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
    port: 8021
# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"