eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
zuul:
  routes:
    api-a:
      path: /pc-app/**
      serviceId: pc-app-service
  #我们在使用Nginx的时候，会涉及到一个请求头信息的配置，
  #防止页面重定向后跳转到上游服务器上去，
  #这个问题在Zuul中一样存在，假设我的feign-consumer中提供了一个接口/hello4，
  #当访问/hello4接口的时候，页面重定向到/hello，默认情况下，
  #重定向的地址是具体的服务实例的地址，而不是API网关的跳转地址，
  #这种做法会暴露真实的服务地址.
  add-host-header:  true  
  #默认情况下，敏感的头信息无法经过API网关进行传递，我们可以通过如下配置使之可以传递：
  #name:  
  #   sensitiveHeaders:  
  #
# 关闭Hystrix重试机制  
# retryable: false 全局   name.retryable 某个
#   连接本地controller时,因为在Filter 中 读取了request信息 导致 forward:转向时报错 暂时无法解决
#    local:  
#      path: /local/**
#      url:  forward:/local

#zuul.ignored-services=hello-service #跳过 hello-service服务,不为其创建路由规则
#zuul.ignored-patterns=/**/hello/** 不给/hello接口路由
spring: 
  rabbitmq: 
    host: localhost
    port: 5672
    username: appusername
    password: pdf8371759