eureka: 
  instance: 
    environment: dev
  server: 
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false 
server: 
  port: 8761
spring: 
  application: 
    name: multi-eureka-server
  #会检查终端是否支持ANSI，是的话就采用彩色输出
  output: 
    ansi: 
      enabled:  DETECT
logging:
    #配置日志基本地址
    home: C:/Users/Administrator/Desktop/Log/${spring.application.name}